### ISSUE TITLE
Can't activate plugin in Blender 3.6

### ISSUE THREAD

**Issue by neopostmodern** [folkertdev/freestyle-svg-exporter#23]
When I try to activate the addon in settings I get:
```
Traceback (most recent call last):
  File "/home/neopostmodern/Applications/blender-3.6.2-linux-x64/3.6/scripts/modules/addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "/home/neopostmodern/Applications/blender-3.6.2-linux-x64/3.6/scripts/addons/render_freestyle_svg.py", line 17, in <module>
    import parameter_editor
  File "/home/neopostmodern/Applications/blender-3.6.2-linux-x64/3.6/scripts/freestyle/modules/parameter_editor.py", line 55, in <module>
    from freestyle.shaders import (
ImportError: cannot import name 'StrokeShader' from 'freestyle.shaders' (/home/neopostmodern/.local/lib/python3.10/site-packages/freestyle/shaders.py)
```

**Comment by neopostmodern** [comment]
Works with 3.4 on the same machine
